// src/pages/admin/MindtAdmin.jsx 
import React from "react";
import {
  FaUserShield,
  FaTools,
  FaChartLine,
  FaUserEdit,
  FaRegClock,
} from "react-icons/fa";
import { useNavigate } from "react-router-dom";

const MindtAdmin = () => {
  const navigate = useNavigate();

  const handleProfilesClick = () => {
    navigate("/Mindt-admin/profiles");
  };

  return (
    <div className="p-6">
      <h1 className="text-2xl font-bold mb-6 flex items-center gap-2">
        🧠 MindtPanel – Wellness Admin Dashboard
      </h1>

      {/* Admin Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mb-10">
        <div
          className="bg-zinc-800 p-4 rounded-lg hover:bg-zinc-700 cursor-pointer transition"
          onClick={handleProfilesClick}
        >
          <h2 className="text-lg font-semibold flex items-center gap-2 mb-2">
            <FaUserShield /> Public Profiles
          </h2>
          <p className="text-zinc-400 text-sm">
            View and manage all user-created public profiles for the Mindt program.
          </p>
          <button className="mt-4 bg-purple-600 hover:bg-purple-700 text-white px-4 py-2 rounded">
            Open section
          </button>
        </div>

        <div
          className="bg-zinc-800 p-4 rounded-lg hover:bg-zinc-700 cursor-pointer transition"
          onClick={() => navigate("/Mindt-admin/kpi")}
        >
          <h2 className="text-lg font-semibold flex items-center gap-2 mb-2">
            📊 Business Intelligence
          </h2>
          <p className="text-zinc-400 text-sm">
            Visualizza KPI, click, view e metriche interattive delle CTA Mindt.
          </p>
          <button className="mt-4 bg-purple-600 hover:bg-purple-700 text-white px-4 py-2 rounded">
            View KPI
          </button>
        </div>

        <div className="bg-zinc-800 p-4 rounded-lg opacity-60">
          <h2 className="text-lg font-semibold flex items-center gap-2 mb-2">
            <FaChartLine /> Activity Monitor
          </h2>
          <p className="text-zinc-400 text-sm">Track user progress and milestones.</p>
          <span className="mt-4 inline-block text-xs bg-zinc-700 text-white px-3 py-1 rounded">
            Coming soon
          </span>
        </div>

        <div className="bg-zinc-800 p-4 rounded-lg opacity-60">
          <h2 className="text-lg font-semibold flex items-center gap-2 mb-2">
            <FaUserEdit /> Assistant Logs
          </h2>
          <p className="text-zinc-400 text-sm">Review responses generated by the AI assistant.</p>
          <span className="mt-4 inline-block text-xs bg-zinc-700 text-white px-3 py-1 rounded">
            Coming soon
          </span>
        </div>

        <div className="bg-zinc-800 p-4 rounded-lg opacity-60">
          <h2 className="text-lg font-semibold flex items-center gap-2 mb-2">
            <FaTools /> Internal Tools
          </h2>
          <p className="text-zinc-400 text-sm">Administrative utilities and reports.</p>
          <span className="mt-4 inline-block text-xs bg-zinc-700 text-white px-3 py-1 rounded">
            Coming soon
          </span>
        </div>

        <div className="bg-zinc-800 p-4 rounded-lg opacity-60">
          <h2 className="text-lg font-semibold flex items-center gap-2 mb-2">
            <FaRegClock /> User History
          </h2>
          <p className="text-zinc-400 text-sm">Logs of user actions within the wellness module.</p>
          <span className="mt-4 inline-block text-xs bg-zinc-700 text-white px-3 py-1 rounded">
            Coming soon
          </span>
        </div>
      </div>
    </div>
  );
};

export default MindtAdmin;
